//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SmsForward
    {
        public int ID { get; set; }
        public string so_tien { get; set; }
        public string ten_bank { get; set; }
        public string ma_gd { get; set; }
        public string noi_dung { get; set; }
        public string soDu_bank { get; set; }
        public string thoi_gian { get; set; }
        public string trans_id { get; set; }
        public string ma_baoMat { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public string Username { get; set; }
    }
}
